# Generated by Django 5.0 on 2024-01-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('rating_rate', models.FloatField()),
                ('rating_count', models.IntegerField()),
            ],
        ),
    ]
