# Generated by Django 5.0 on 2024-01-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating_rate',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('unreleased', '0'), ('released', '1'), ('unstore', '2'), ('storing', '3'), ('instore', '4')], default=0, max_length=255),
            preserve_default=False,
        ),
    ]
