# Generated by Django 5.0 on 2024-01-01 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_rating_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
