# Generated by Django 5.0 on 2024-01-01 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_last_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('0', '未发布'), ('1', '已发布'), ('2', '未入库'), ('3', '入库中'), ('4', '已入库')], max_length=255),
        ),
    ]
