# Generated by Django 5.0 on 2024-01-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='是否有效'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='产品图片'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_change',
            field=models.DateTimeField(auto_now=True, verbose_name='上次修改在'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('0', '未发布'), ('1', '已发布'), ('2', '未入库'), ('3', '入库中'), ('4', '已入库')], max_length=255, verbose_name='产品状态'),
        ),
    ]
