# Generated by Django 5.0 on 2024-01-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_valid_alter_product_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_change_by',
            field=models.CharField(default='System', max_length=255, verbose_name='上次修改人员'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='产品描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='产品图片'),
        ),
    ]
